from common_utils import (
    print_tensor_recursive,
    compute_output_shape,
    panic,
    log_debug,
    variadic1or2,
    Slicer,
    i,
    s,
    newaxis,
    Idx,
    NewAxis,
    is_power_of_two,
    validate_matrix_shapes,
    variadiclist_as_intlist,
    is_null,
    id,
)
