from common_utils import (
    Validator,
    compute_output_shape,
    panic,
    log_debug,
    variadic1or2,
    Slicer,
    i,
    s,
    newaxis,
    Idx,
    NewAxis,
    is_power_of_two,
    validate_matrix_shapes,
)
