comptime Noop = 0
comptime MulTensor = 1
comptime AddTensor = 2
comptime SubtractTensor = 3
comptime ZeroGrad = 4
comptime Add = 5
comptime Subtract = 6
comptime ReverseSubtract = 7
comptime Multiply = 8
comptime Divide = 9
comptime ReverseDivide = 10
comptime Equal = 11
comptime NotEqual = 12
comptime LessThan = 13
comptime LessThanEqual = 14
comptime GreaterThan = 15
comptime GreaterThanEqual = 16
comptime Overwrite = 17
comptime SigmoidOp = 18
comptime Log = 19
comptime Exp = 20
comptime TanhForwardOp = 21
comptime TanhBackwardOp = 22
comptime ReLUForwardOp = 23
comptime ReLUBackwardOp = 24
comptime SqrtForwardOp = 25
comptime SqrtBackwardOp = 26
###################
### matul ###########
comptime dot = 27  # dot product
comptime vm = 28  # vector & tensor matmul
comptime mv = 29  # tensor & vector matmul
comptime mm = 30  # tensor & tensor matmul
comptime invalid = 31  # Invalid case
