from tenmo.tensor import Tensor

fn main():
    var t = Tensor[DType.float32].d2([[1.0, 2.0, 3.0, 4.0], [1.0, 2.0, 3.0, 4.0], [1.0, 2.0, 3.0, 4.0]])
    print("Input shape:", t.shape())
    var p0 = t.product(axes=[0])
    print("Product along axis 0:")
    p0.print()
    print("  expected: [1.0, 8.0, 27.0, 64.0]")
    var p1 = t.product(axes=[1])
    print("Product along axis 1:")
    p1.print()
    print("  expected: [24.0, 24.0, 24.0]")
    var pall = t.product(axes=[])
    print("Product all:")
    pall.print()
    print("  expected: 13824.0")
    var pk = t.product(axes=[0], keepdims=True)
    print("Product with keepdims:")
    pk.print()
    print("  shape:", pk.shape())
