"""Mnemonics for tensor operations - internal constants used by the autograd engine.
"""
comptime Noop = 0
comptime MulTensor = 1
comptime AddTensor = 2
comptime SubtractTensor = 3
comptime ZeroGrad = 4
comptime Add = 5
comptime Subtract = 6
comptime ReverseSubtract = 7
comptime Multiply = 8
comptime Divide = 9
comptime ReverseDivide = 10
comptime Equal = 11
comptime NotEqual = 12
comptime LessThan = 13
comptime LessThanEqual = 14
comptime GreaterThan = 15
comptime GreaterThanEqual = 16
comptime Overwrite = 17
comptime RELU_FORWARD = 18
comptime RELU_BACKWARD = 19
comptime SQRT = 20
comptime SQRT_BACKWARD = 21
comptime LOG = 22
comptime dot = 23  # dot product
comptime vm = 24  # vector & tensor matmul
comptime mv = 25  # tensor & vector matmul
comptime mm = 26  # tensor & tensor matmul
comptime invalid = 27  # Invalid case


comptime LINEAR = 28 #Net
comptime LINEAR_BLAS = 29
comptime RELU = 30
comptime SIGMOID = 31
comptime TANH = 32
comptime DROPOUT = 33
comptime CONV2D = 34
comptime FLATTEN = 35
comptime MAXPOOL2D = 36
comptime LAYER_NORM = 37

comptime max_rank = 8  # Change this to extend/reduce max supported dimension
comptime EXP = 38
comptime NEGATE = 39
comptime ABS = 40
comptime MAX = 41
comptime MIN = 42
comptime POW = 43
comptime TANH_FORWARD = 44
comptime SIGMOID_FORWARD = 45
comptime SIGMOID_BACKWARD = 46
comptime TANH_BACKWARD = 47
comptime LOG_BACKWARD = 48
comptime INVERT = 49
comptime SUM = 50
comptime MEAN = 51
comptime PRODUCT = 52
