"""Mnemonics for tensor operations - internal constants used by the autograd engine.
"""
comptime Noop = 0
comptime MulTensor = 1
comptime AddTensor = 2
comptime SubtractTensor = 3
comptime ZeroGrad = 4
comptime ScatterAddTensor = 5
comptime Add = 6
comptime Subtract = 7
comptime ReverseSubtract = 8
comptime Multiply = 9
comptime Divide = 10
comptime ReverseDivide = 11
comptime Equal = 12
comptime NotEqual = 13
comptime LessThan = 14
comptime LessThanEqual = 15
comptime GreaterThan = 16
comptime GreaterThanEqual = 17
comptime Overwrite = 18
comptime RELU_FORWARD = 19
comptime RELU_BACKWARD = 20
comptime SQRT = 21
comptime SQRT_BACKWARD = 22
comptime LOG = 23
comptime dot = 24  # dot product
comptime vm = 25  # vector & tensor matmul
comptime mv = 26  # tensor & vector matmul
comptime mm = 27  # tensor & tensor matmul
comptime invalid = 28  # Invalid case


comptime LINEAR = 29 #Net
comptime LINEAR_BLAS = 30
comptime RELU = 31
comptime SIGMOID = 32
comptime TANH = 33
comptime DROPOUT = 34
comptime CONV2D = 35
comptime FLATTEN = 36
comptime MAXPOOL2D = 37
comptime LAYER_NORM = 38

comptime max_rank = 8  # Change this to extend/reduce max supported dimension
comptime EXP = 39
comptime NEGATE = 40
comptime ABS = 41
comptime MAX = 42
comptime MIN = 43
comptime POW = 44
comptime TANH_FORWARD = 45
comptime SIGMOID_FORWARD = 46
comptime SIGMOID_BACKWARD = 47
comptime TANH_BACKWARD = 48
comptime LOG_BACKWARD = 49
comptime INVERT = 50
comptime SUM = 51
comptime MEAN = 52
comptime PRODUCT = 53
